#ifndef LABELS_H
#define LABELS_H

typedef struct {
	const char *label;
	int value;
} label_t;

#define KEY_LABELS_COUNT (sizeof(key_labels) / sizeof(key_labels[0]))

label_t key_labels = {
	{ "KEY_ESC", 1, N_("Esc") },
	{ "KEY_1", 2, "1" },
	{ "KEY_2", 3, "2" },
	{ "KEY_3", 4, "3" },
	{ "KEY_4", 5, "4" },
	{ "KEY_5", 6, "5" },
	{ "KEY_6", 7, "6" },
	{ "KEY_7", 8, "7" },
	{ "KEY_8", 9, "8" },
	{ "KEY_9", 10, "9" },
	{ "KEY_0", 11, "0" },
	{ "KEY_MINUS", 12, "-" },
	{ "KEY_EQUAL", 13, "=" },
	{ "KEY_BACKSPACE", 14, N_("Backspace") },
	{ "KEY_TAB", 15, N_("Tab") },
	{ "KEY_Q", 16, "Q" },
	{ "KEY_W", 17, "W" },
	{ "KEY_E", 18, "E" },
	{ "KEY_R", 19, "R" },
	{ "KEY_T", 20, "T" },
	{ "KEY_Y", 21, "Y" },
	{ "KEY_U", 22, "U" },
	{ "KEY_I", 23, "I" },
	{ "KEY_O", 24, "O" },
	{ "KEY_P", 25, "P" },
	{ "KEY_LEFTBRACE", 26, "[" },
	{ "KEY_RIGHTBRACE", 27, "]" },
	{ "KEY_ENTER", 28, N_("Enter") },
	{ "KEY_LEFTCTRL", 29, N_("Left Ctrl") },
	{ "KEY_A", 30, "A" },
	{ "KEY_S", 31, "S" },
	{ "KEY_D", 32, "D" },
	{ "KEY_F", 33, "F" },
	{ "KEY_G", 34, "G" },
	{ "KEY_H", 35, "H" },
	{ "KEY_J", 36, "J" },
	{ "KEY_K", 37, "K" },
	{ "KEY_L", 38, "L" },
	{ "KEY_SEMICOLON", 39, ";" },
	{ "KEY_APOSTROPHE", 40, "'" },
	{ "KEY_GRAVE", 41, "`" },
	{ "KEY_LEFTSHIFT", 42, N_("Left Shift") },
	{ "KEY_BACKSLASH", 43, "\\" },
	{ "KEY_Z", 44, "Z" },
	{ "KEY_X", 45, "X" },
	{ "KEY_C", 46, "C" },
	{ "KEY_V", 47, "V" },
	{ "KEY_B", 48, "B" },
	{ "KEY_N", 49, "N" },
	{ "KEY_M", 50, "M" },
	{ "KEY_COMMA", 51, "," },
	{ "KEY_DOT", 52, "." },
	{ "KEY_SLASH", 53, "/" },
	{ "KEY_RIGHTSHIFT", 54, N_("Right Shift") },
	{ "KEY_KPASTERISK", 55, N_("Keypad *") },
	{ "KEY_LEFTALT", 56, N_("Left Alt") },
	{ "KEY_SPACE", 57, N_("Space") },
	{ "KEY_CAPSLOCK", 58, N_("Caps Lock") },
	{ "KEY_F1", 59, "F1" },
	{ "KEY_F2", 60, "F2" },
	{ "KEY_F3", 61, "F3" },
	{ "KEY_F4", 62, "F4" },
	{ "KEY_F5", 63, "F5" },
	{ "KEY_F6", 64, "F6" },
	{ "KEY_F7", 65, "F7" },
	{ "KEY_F8", 66, "F8" },
	{ "KEY_F9", 67, "F9" },
	{ "KEY_F10", 68, "F10" },
	{ "KEY_NUMLOCK", 69, N_("Num Lock") },
	{ "KEY_SCROLLLOCK", 70, N_("Scroll Lock") },
	{ "KEY_KP7", 71, N_("Keypad 7") },
	{ "KEY_KP8", 72, N_("Keypad 8") },
	{ "KEY_KP9", 73, N_("Keypad 9") },
	{ "KEY_KPMINUS", 74, N_("Keypad -") },
	{ "KEY_KP4", 75, N_("Keypad 4") },
	{ "KEY_KP5", 76, N_("Keypad 5") },
	{ "KEY_KP6", 77, N_("Keypad 6") },
	{ "KEY_KPPLUS", 78, N_("Keypad +") },
	{ "KEY_KP1", 79, N_("Keypad 1") },
	{ "KEY_KP2", 80, N_("Keypad 2") },
	{ "KEY_KP3", 81, N_("Keypad 3") },
	{ "KEY_KP0", 82, N_("Keypad 0") },
	{ "KEY_KPDOT", 83, N_("Keypad .") },
	{ "KEY_ZENKAKUHANKAKU", 85, N_("") },
	{ "KEY_102ND", 86, N_("") },
	{ "KEY_F11", 87, N_("F11") },
	{ "KEY_F12", 88, N_("F12") },
	{ "KEY_RO", 89, N_("") },
	{ "KEY_KATAKANA", 90, N_("") },
	{ "KEY_HIRAGANA", 91, N_("") },
	{ "KEY_HENKAN", 92, N_("") },
	{ "KEY_KATAKANAHIRAGANA", 93, N_("") },
	{ "KEY_MUHENKAN", 94, N_("") },
	{ "KEY_KPJPCOMMA", 95, N_("") },
	{ "KEY_KPENTER", 96, N_("Keypad Enter") },
	{ "KEY_RIGHTCTRL", 97, N_("Right Ctrl") },
	{ "KEY_KPSLASH", 98, N_("Keypad /") },
	{ "KEY_SYSRQ", 99, N_("SysRq") },
	{ "KEY_RIGHTALT", 100, N_("Right Alt") },
	{ "KEY_LINEFEED", 101, N_("Line Feed") },
	{ "KEY_HOME", 102, N_("Home") },
	{ "KEY_UP", 103, N_("Up") },
	{ "KEY_PAGEUP", 104, N_("Page Up") },
	{ "KEY_LEFT", 105, N_("Left") },
	{ "KEY_RIGHT", 106, N_("Right") },
	{ "KEY_END", 107, N_("End") },
	{ "KEY_DOWN", 108, N_("Down") },
	{ "KEY_PAGEDOWN", 109, N_("Page Down") },
	{ "KEY_INSERT", 110, N_("Insert") },
	{ "KEY_DELETE", 111, N_("Delete") },
	{ "KEY_MACRO", 112, N_("Macro") },
	{ "KEY_MUTE", 113, N_("Mute") },
	{ "KEY_VOLUMEDOWN", 114, N_("Volume Down") },
	{ "KEY_VOLUMEUP", 115, N_("Volume Up") },
	{ "KEY_POWER", 116, N_("Power") },
	{ "KEY_KPEQUAL", 117, N_("Keypad =") },
	{ "KEY_KPPLUSMINUS", 118, N_("Keypad ±") },
	{ "KEY_PAUSE", 119, N_("Pause") },
	{ "KEY_KPCOMMA", 121, N_("Keypad .") },
	{ "KEY_HANGEUL", 122, N_("") },
	{ "KEY_HANGUEL", 122, N_("") },
	{ "KEY_HANJA", 123, N_("") },
	{ "KEY_YEN", 124, N_("") },
	{ "KEY_LEFTMETA", 125, N_("Left Meta") },
	{ "KEY_RIGHTMETA", 126, N_("Right Meta") },
	{ "KEY_COMPOSE", 127, N_("Compose") },
	{ "KEY_STOP", 128, N_("Stop") },
	{ "KEY_AGAIN", 129, N_("Again") },
	{ "KEY_PROPS", 130, N_("") },
	{ "KEY_UNDO", 131, N_("Undo") },
	{ "KEY_FRONT", 132, N_("") },
	{ "KEY_COPY", 133, N_("Copy") },
	{ "KEY_OPEN", 134, N_("Open") },
	{ "KEY_PASTE", 135, N_("Paste") },
	{ "KEY_FIND", 136, N_("Find") },
	{ "KEY_CUT", 137, N_("Cut") },
	{ "KEY_HELP", 138, N_("Help") },
	{ "KEY_MENU", 139, N_("Menu") },
	{ "KEY_CALC", 140, N_("") },
	{ "KEY_SETUP", 141, N_("Setup") },
	{ "KEY_SLEEP", 142, N_("Sleep") },
	{ "KEY_WAKEUP", 143, N_("Wake Up") },
	{ "KEY_FILE", 144, N_("File") },
	{ "KEY_SENDFILE", 145, N_("Send File") },
	{ "KEY_DELETEFILE", 146, N_("Delete File") },
	{ "KEY_XFER", 147, N_("Transfer") },
	{ "KEY_PROG1", 148, N_("") },
	{ "KEY_PROG2", 149, N_("") },
	{ "KEY_WWW", 150, N_("WWW") },
	{ "KEY_MSDOS", 151, N_("MS-DOS") },
	{ "KEY_COFFEE", 152, N_("Coffee") },
	{ "KEY_SCREENLOCK", 152, N_("Screen Lock") },
	{ "KEY_DIRECTION", 153, N_("Direction") },
	{ "KEY_CYCLEWINDOWS", 154, N_("Cycle Windows") },
	{ "KEY_MAIL", 155, N_("Mail") },
	{ "KEY_BOOKMARKS", 156, N_("Bookmarks") },
	{ "KEY_COMPUTER", 157, N_("Computer") },
	{ "KEY_BACK", 158, N_("Back") },
	{ "KEY_FORWARD", 159, N_("Forward") },
	{ "KEY_CLOSECD", 160, N_("Close CD") },
	{ "KEY_EJECTCD", 161, N_("Eject CD") },
	{ "KEY_EJECTCLOSECD", 162, N_("Eject/Close CD") },
	{ "KEY_NEXTSONG", 163, N_("Next Song") },
	{ "KEY_PLAYPAUSE", 164, N_("Play/Pause") },
	{ "KEY_PREVIOUSSONG", 165, N_("Previous Song") },
	{ "KEY_STOPCD", 166, N_("Stop CD") },
	{ "KEY_RECORD", 167, N_("Record") },
	{ "KEY_REWIND", 168, N_("Rewind") },
	{ "KEY_PHONE", 169, N_("Phone") },
	{ "KEY_ISO", 170, N_("") },
	{ "KEY_CONFIG", 171, N_("") },
	{ "KEY_HOMEPAGE", 172, N_("") },
	{ "KEY_REFRESH", 173, N_("Refresh") },
	{ "KEY_EXIT", 174, N_("Exit") },
	{ "KEY_MOVE", 175, N_("Move") },
	{ "KEY_EDIT", 176, N_("Edit") },
	{ "KEY_SCROLLUP", 177, N_("Scroll Up") },
	{ "KEY_SCROLLDOWN", 178, N_("Scroll Down") },
	{ "KEY_KPLEFTPAREN", 179, N_("Keypad (") },
	{ "KEY_KPRIGHTPAREN", 180, N_("Keypad )") },
	{ "KEY_NEW", 181, N_("New") },
	{ "KEY_REDO", 182, N_("Redo") },
	{ "KEY_F13", 183, "F13" },
	{ "KEY_F14", 184, "F14" },
	{ "KEY_F15", 185, "F15" },
	{ "KEY_F16", 186, "F16" },
	{ "KEY_F17", 187, "F17" },
	{ "KEY_F18", 188, "F18" },
	{ "KEY_F19", 189, "F19" },
	{ "KEY_F20", 190, "F20" },
	{ "KEY_F21", 191, "F21" },
	{ "KEY_F22", 192, "F22" },
	{ "KEY_F23", 193, "F23" },
	{ "KEY_F24", 194, "F24" },
	{ "KEY_PLAYCD", 200, N_("Play CD") },
	{ "KEY_PAUSECD", 201, N_("Pause CD") },
	{ "KEY_PROG3", 202, N_("") },
	{ "KEY_PROG4", 203, N_("") },
	{ "KEY_SUSPEND", 205, N_("Suspend") },
	{ "KEY_CLOSE", 206, N_("Close") },
	{ "KEY_PLAY", 207, N_("Play") },
	{ "KEY_FASTFORWARD", 208, N_("Fast Forward") },
	{ "KEY_BASSBOOST", 209, N_("Bass Boost") },
	{ "KEY_PRINT", 210, N_("Print") },
	{ "KEY_HP", 211, N_("") },
	{ "KEY_CAMERA", 212, N_("Camera") },
	{ "KEY_SOUND", 213, N_("Sound") },
	{ "KEY_QUESTION", 214, N_("Question") },
	{ "KEY_EMAIL", 215, N_("E-mail") },
	{ "KEY_CHAT", 216, N_("Chat") },
	{ "KEY_SEARCH", 217, N_("Search") },
	{ "KEY_CONNECT", 218, N_("Connect") },
	{ "KEY_FINANCE", 219, N_("Finance") },
	{ "KEY_SPORT", 220, N_("Sport") },
	{ "KEY_SHOP", 221, N_("Shop") },
	{ "KEY_ALTERASE", 222, N_("") },
	{ "KEY_CANCEL", 223, N_("Cancel") },
	{ "KEY_BRIGHTNESSDOWN", 224, N_("Brightness Down") },
	{ "KEY_BRIGHTNESSUP", 225, N_("Brightness Up") },
	{ "KEY_MEDIA", 226, N_("Media") },
	{ "KEY_SWITCHVIDEOMODE", 227, N_("Switch Video Mode") },
	{ "KEY_KBDILLUMTOGGLE", 228, N_("") },
	{ "KEY_KBDILLUMDOWN", 229, N_("") },
	{ "KEY_KBDILLUMUP", 230, N_("") },
	{ "KEY_SEND", 231, N_("Send") },
	{ "KEY_REPLY", 232, N_("Reply") },
	{ "KEY_FORWARDMAIL", 233, N_("Forward Mail") },
	{ "KEY_SAVE", 234, N_("Save") },
	{ "KEY_DOCUMENTS", 235, N_("Documents") },
	{ "KEY_BATTERY", 236, N_("Battery") },
	{ "KEY_BLUETOOTH", 237, N_("Bluetooth") },
	{ "KEY_WLAN", 238, N_("WLAN") },
	{ "KEY_UWB", 239, N_("UWB") },
	{ "KEY_UNKNOWN", 240, N_("") },
	{ "KEY_VIDEO_NEXT", 241, N_("") },
	{ "KEY_VIDEO_PREV", 242, N_("") },
	{ "KEY_BRIGHTNESS_CYCLE", 243, N_("") },
	{ "KEY_BRIGHTNESS_ZERO", 244, N_("") },
	{ "KEY_DISPLAY_OFF", 245, N_("") },

	{ "KEY_OK", 0x160, N_("OK") },
	{ "KEY_SELECT", 0x161, N_("Select") },
	{ "KEY_GOTO", 0x162, N_("Goto") },
	{ "KEY_CLEAR", 0x163, N_("Clear") },
	{ "KEY_POWER2", 0x164, N_("") },
	{ "KEY_OPTION", 0x165, N_("Option") },
	{ "KEY_INFO", 0x166, N_("") },
	{ "KEY_TIME", 0x167, N_("") },
	{ "KEY_VENDOR", 0x168, N_("") },
	{ "KEY_ARCHIVE", 0x169, N_("") },
	{ "KEY_PROGRAM", 0x16a, N_("") },
	{ "KEY_CHANNEL", 0x16b, N_("") },
	{ "KEY_FAVORITES", 0x16c, N_("") },
	{ "KEY_EPG", 0x16d, N_("") },
	{ "KEY_PVR", 0x16e, N_("") },
	{ "KEY_MHP", 0x16f, N_("") },
	{ "KEY_LANGUAGE", 0x170, N_("") },
	{ "KEY_TITLE", 0x171, N_("") },
	{ "KEY_SUBTITLE", 0x172, N_("") },
	{ "KEY_ANGLE", 0x173, N_("") },
	{ "KEY_ZOOM", 0x174, N_("") },
	{ "KEY_MODE", 0x175, N_("") },
	{ "KEY_KEYBOARD", 0x176, N_("") },
	{ "KEY_SCREEN", 0x177, N_("") },
	{ "KEY_PC", 0x178, N_("") },
	{ "KEY_TV", 0x179, N_("") },
	{ "KEY_TV2", 0x17a, N_("") },
	{ "KEY_VCR", 0x17b, N_("") },
	{ "KEY_VCR2", 0x17c, N_("") },
	{ "KEY_SAT", 0x17d, N_("") },
	{ "KEY_SAT2", 0x17e, N_("") },
	{ "KEY_CD", 0x17f, N_("") },
	{ "KEY_TAPE", 0x180, N_("") },
	{ "KEY_RADIO", 0x181, N_("") },
	{ "KEY_TUNER", 0x182, N_("") },
	{ "KEY_PLAYER", 0x183, N_("") },
	{ "KEY_TEXT", 0x184, N_("") },
	{ "KEY_DVD", 0x185, N_("") },
	{ "KEY_AUX", 0x186, N_("") },
	{ "KEY_MP3", 0x187, N_("") },
	{ "KEY_AUDIO", 0x188, N_("") },
	{ "KEY_VIDEO", 0x189, N_("") },
	{ "KEY_DIRECTORY", 0x18a, N_("") },
	{ "KEY_LIST", 0x18b, N_("") },
	{ "KEY_MEMO", 0x18c, N_("") },
	{ "KEY_CALENDAR", 0x18d, N_("") },
	{ "KEY_RED", 0x18e, N_("") },
	{ "KEY_GREEN", 0x18f, N_("") },
	{ "KEY_YELLOW", 0x190, N_("") },
	{ "KEY_BLUE", 0x191, N_("") },
	{ "KEY_CHANNELUP", 0x192, N_("") },
	{ "KEY_CHANNELDOWN", 0x193, N_("") },
	{ "KEY_FIRST", 0x194, N_("") },
	{ "KEY_LAST", 0x195, N_("") },
	{ "KEY_AB", 0x196, N_("") },
	{ "KEY_NEXT", 0x197, N_("") },
	{ "KEY_RESTART", 0x198, N_("") },
	{ "KEY_SLOW", 0x199, N_("") },
	{ "KEY_SHUFFLE", 0x19a, N_("") },
	{ "KEY_BREAK", 0x19b, N_("") },
	{ "KEY_PREVIOUS", 0x19c, N_("") },
	{ "KEY_DIGITS", 0x19d, N_("") },
	{ "KEY_TEEN", 0x19e, N_("") },
	{ "KEY_TWEN", 0x19f, N_("") },
	{ "KEY_VIDEOPHONE", 0x1a0, N_("") },
	{ "KEY_GAMES", 0x1a1, N_("") },
	{ "KEY_ZOOMIN", 0x1a2, N_("") },
	{ "KEY_ZOOMOUT", 0x1a3, N_("") },
	{ "KEY_ZOOMRESET", 0x1a4, N_("") },
	{ "KEY_WORDPROCESSOR", 0x1a5, N_("") },
	{ "KEY_EDITOR", 0x1a6, N_("") },
	{ "KEY_SPREADSHEET", 0x1a7, N_("") },
	{ "KEY_GRAPHICSEDITOR", 0x1a8, N_("") },
	{ "KEY_PRESENTATION", 0x1a9, N_("") },
	{ "KEY_DATABASE", 0x1aa, N_("") },
	{ "KEY_NEWS", 0x1ab, N_("") },
	{ "KEY_VOICEMAIL", 0x1ac, N_("") },
	{ "KEY_ADDRESSBOOK", 0x1ad, N_("") },
	{ "KEY_MESSENGER", 0x1ae, N_("") },
	{ "KEY_DISPLAYTOGGLE", 0x1af, N_("") },
	{ "KEY_SPELLCHECK", 0x1b0, N_("") },
	{ "KEY_LOGOFF", 0x1b1, N_("") },
	{ "KEY_DOLLAR", 0x1b2, N_("") },
	{ "KEY_EURO", 0x1b3, N_("") },
	{ "KEY_FRAMEBACK", 0x1b4, N_("") },
	{ "KEY_FRAMEFORWARD", 0x1b5, N_("") },
	{ "KEY_CONTEXT_MENU", 0x1b6, N_("") },
	{ "KEY_DEL_EOL", 0x1c0, N_("") },
	{ "KEY_DEL_EOS", 0x1c1, N_("") },
	{ "KEY_INS_LINE", 0x1c2, N_("") },
	{ "KEY_DEL_LINE", 0x1c3, N_("") },
	{ "KEY_FN", 0x1d0, "Fn" },
	{ "KEY_FN_ESC", 0x1d1, N_("") },
	{ "KEY_FN_F1", 0x1d2, N_("") },
	{ "KEY_FN_F2", 0x1d3, N_("") },
	{ "KEY_FN_F3", 0x1d4, N_("") },
	{ "KEY_FN_F4", 0x1d5, N_("") },
	{ "KEY_FN_F5", 0x1d6, N_("") },
	{ "KEY_FN_F6", 0x1d7, N_("") },
	{ "KEY_FN_F7", 0x1d8, N_("") },
	{ "KEY_FN_F8", 0x1d9, N_("") },
	{ "KEY_FN_F9", 0x1da, N_("") },
	{ "KEY_FN_F10", 0x1db, N_("") },
	{ "KEY_FN_F11", 0x1dc, N_("") },
	{ "KEY_FN_F12", 0x1dd, N_("") },
	{ "KEY_FN_1", 0x1de, N_("") },
	{ "KEY_FN_2", 0x1df, N_("") },
	{ "KEY_FN_D", 0x1e0, N_("") },
	{ "KEY_FN_E", 0x1e1, N_("") },
	{ "KEY_FN_F", 0x1e2, N_("") },
	{ "KEY_FN_S", 0x1e3, N_("") },
	{ "KEY_FN_B", 0x1e4, N_("") },
	{ "KEY_BRL_DOT1", 0x1f1, N_("") },
	{ "KEY_BRL_DOT2", 0x1f2, N_("") },
	{ "KEY_BRL_DOT3", 0x1f3, N_("") },
	{ "KEY_BRL_DOT4", 0x1f4, N_("") },
	{ "KEY_BRL_DOT5", 0x1f5, N_("") },
	{ "KEY_BRL_DOT6", 0x1f6, N_("") },
	{ "KEY_BRL_DOT7", 0x1f7, N_("") },
	{ "KEY_BRL_DOT8", 0x1f8, N_("") },
	{ "KEY_BRL_DOT9", 0x1f9, N_("") },
	{ "KEY_BRL_DOT10", 0x1fa, N_("") },
};

#endif /* LABELS_H */
